### ISSUE TITLE
More README instructions

### ISSUE THREAD

**Issue by brenobaptista** [edfloreshz/cosmic-app-template#3]
Thanks for putting this together!

Could you update the README to include instructions on how to uninstall? Like deleting the folder and removing `just` will undo everything?

Also, it would be nice if there is a way to use some kind of "development mode", so instead of installing the app directly in the machine we can make changes in the code and see it changing on the fly before we actually make a release. Not sure if it's possible in the Rust environment, I'm not a Rust dev. So for now every time I make a change I have to run `just build-release` and `sudo just install`?

**Comment by edfloreshz** [comment]
You can run `cargo run` anytime you want to test your changes, no need to install every time, to uninstall you can run `sudo just uninstall`, I'll add this to the README.
